name: Ubuntu
on: 
  push:
    branches: masterxx
    tags:
      - 'V*'
env:
  HOME: /home/runner/work/saltwatereos/saltwatereos
jobs:
  buildApp:
    name: library
    # ubuntu-latest (ubuntu-20.04: glibc 2.31), ubuntu-18.04 (glibc 2.27), ubuntu-16.04 (glibc 2.23)
    runs-on: ubuntu-18.04
    env:
      AppInstaller: swEOS-Linux-Installer
      Path_Pythons: /opt/hostedtoolcache/Python
    steps:
      # checkout source code
      - uses: actions/checkout@v2
      
      # # install QT5
      # - name: Install Qt
      #   uses: jurplel/install-qt-action@v2.13.0
      #   with:
      #     version: '5.15.2'
      #     host: 'linux'
      #     target: 'desktop'
      #     dir: '${{ github.workspace }}/QT/'
      
      # # install some useful packages 
      # - name: install dependence
      #   run: |
      #     sudo apt-get update -y
      #     sudo apt-get install -y tcl-dev
      #     sudo snap install cqtdeployer
      # # install dependencies, e.g. VTK, swig
      # - name: install dependencies
      #   run: |
      #     git clone https://github.com/zguoch/dependencies_swEOS.git
      #     cd dependencies_swEOS/ubuntu
      #     unzip -qq VTK8.2.zip
      
      # get short SHA of commit 
      - name: Add SHORT_SHA env property with commit short sha
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: info 
        run: |
          cmake --version
          g++ --version
          echo ${{ github.ref }}
          echo "commit id short" ${SHORT_SHA}
          echo "github tag: " ${GIT_TAG}
          python --version
          ldd --version
      # debug workflow
      - name: install oh my zsh
        run: |
          sudo apt-get install zsh
          sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
