name: Windows
on: 
  push:
    branches: main
    tags:
      - 'V*'
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: Library/build
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64
  PYTHON_PATH: C:/hostedtoolcache/windows/Python/3.8.10/x64
  BASIC_PYTHON: 3.9
  HOME: D:/a/saltwatereos/saltwatereos
  AppInstaller: swEOS-Windows-Installer
jobs:
  buildApp:
    name: library
    runs-on: windows-latest
    # strategy:
    #   matrix:
    #     python:
    #       # - {version: '2.7', lib: 'python27.lib' }
    #       # - {version: '3.5', lib: 'python35.lib' }
    #       # - {version: '3.6', lib: 'python36.lib' }
    #       # - {version: '3.7', lib: 'python37.lib' }
    #       # - {version: '3.8', lib: 'python38.lib' }
    #       - {version: '3.9', lib: 'python39.lib' }
    steps:
      # checkout source code
      - uses: actions/checkout@v2

      # config msbuild
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      # # install Qt5
      # - name: Install Qt
      #   uses: jurplel/install-qt-action@v2.13.0
      #   with:
      #     version: '5.15.2'
      #     host: 'windows'
      #     target: 'desktop'
      #     dir: '${{ github.workspace }}/QT/'

      # # install dependencies, e.g. VTK, swig
      # - name: install dependencies
      #   working-directory: ${{ env.GITHUB_WORKSPACE }}
      #   run: |
      #     git clone https://github.com/zguoch/dependencies_swEOS.git
      #     cd dependencies_swEOS/windows
      #     unzip -qq swigwin-4.0.2.zip
      #     unzip -qq VTK8.2.zip

      # - name: Set up Python version
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python.version }}

      # get short SHA of commit 
      - name: Add SHORT_SHA env property with commit short sha
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: info 
        run: |
          cmake --version
          g++ --version
          echo ${{ github.ref }}
          echo "commit id short" ${SHORT_SHA}
          python --version
      # debug workflow
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
